### ISSUE TITLE
New hackage release (or revision) to use haskell-src-exts-1.22 in hie

### ISSUE THREAD

**Issue by jneira** [fendor/hsimport#23]
Hi! [We are thinking bump up the lower bound of haskell-src-ext to 1.22](https://github.com/haskell/haskell-ide-engine/issues/1649). Unfortunately it need a hackage release or revision of hsimport to include #22 
Thanks in advance!

**Comment by jneira** [comment]
Just in case, the test suite still has the kaskell-src-exts upper bound `< 1.22`. Was it done on purpose?

**Comment by dan-t** [comment]
On Tue, Mar 03, 2020 at 12:20:45AM -0800, Javier Neira wrote:
> Just in case, the test suite still has the kaskell-src-exts upper bound < 1.22. Was it done on purpose?

Looks like an update error. Can you try using 'haskell-src-exts -any'
for the test suite? The version should then be restricted by the
'library' section.

**Comment by fendor** [comment]
I tested to run the tests locally with `haskell-src-exts == 1.23` and tests succeeded.
I think we can get away with just creating a revision on hackage?

**Comment by jneira** [comment]
Hey i've just see [the revision had been done](https://hackage.haskell.org/package/hsimport-0.11.0/revisions/), thanks @fendor!
